version: '3'
services:

  mysql:
    image: mysql:5.6
    volumes:
      - "./data/mysql/:/docker-entrypoint-initdb.d/"
    environment:
      MYSQL_ROOT_PASSWORD: joinMonster
      MYSQL_DATABASE: join_monster

  monster:
    build: ./
    volumes:
      - "./:/home/node/app/"
      - /home/node/app/node_modules
    environment:
      NODE_ENV: development
      DEBUG: join-monster
      JM_DB: mysql2
      # JM_DB: pg
      # DATABASE_URL: postgres://postgres:postgres@postgres/postgres
    ports:
      - '3000:3000'
    depends_on:
      - mysql

  # postgres:
  #   image: postgres:9.6.3
  #     volumes:
  #       - "./data/paginated-demo-dump.sql:/docker-entrypoint-initdb.d/paginated-demo-dump.sql"